### ISSUE TITLE
Pair ABX Test

### ISSUE THREAD

**Issue by jaakkopasanen** [jaakkopasanen/ABX#1]
Paired ABX test works like regular ABX test but with the difference that X is never one of the options A, B, C, ... but instead a pair audio sample of one of these. The user's task is to tell if X is closest to A, B or C. Correct selection means the user chose the option which is the pair of the randomly selected X.

Configuration would look something like this
```yaml
tests:
  name: Transducer test
  type: PairABX
  optionPairs:
    - reference: song-1-transducer-1
      choice: song-2-transducer-1
    - reference: song-1-transducer-2
      choice: song-2-transducer-2
```
Options `song-1-transducer-1` and `song-1-transducer-2` are always the fixed A and B references. The test randomly selects either `song-2-transducer-1` or `song-2-transducer-2`. The randomly selected X would sound more similar to either A or B because they are recodings of the same audio clip played by different transducer. User's task is essentially to tell if X is a recording of `transducer-1` or `transducer-2`.
